# Generated by Django 4.2.17 on 2025-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_body_review_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='body',
        ),
    ]
