# Generated by Django 4.2.17 on 2025-01-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_table_delete_bookingsystem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='max_people',
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
