# Generated by Django 4.2.17 on 2025-01-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_table_max_people_table_date_table_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
