# Generated by Django 4.2.17 on 2025-01-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_table_customer_table_date_alter_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='customer',
            field=models.CharField(default='customer full name', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
