# Generated by Django 4.2.17 on 2025-01-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_table_customer_alter_table_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='customer',
            new_name='title',
        ),
    ]
