# Generated by Django 4.2.17 on 2025-01-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_customer_table_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='title',
            new_name='customer',
        ),
    ]
