# Generated by Django 4.2.17 on 2025-01-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_table_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(default='12PM', max_length=10),
        ),
    ]
