# Generated by Django 4.2.17 on 2025-01-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_reservation_delete_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=10),
        ),
    ]
