# Generated by Django 4.2.17 on 2025-01-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_alter_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
