# Generated by Django 4.2.17 on 2025-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_reservation_number_of_guests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('seats', models.IntegerField()),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
            ],
        ),
    ]
