# Generated by Django 4.2.17 on 2025-09-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.table'),
        ),
    ]
