# Generated by Django 4.2.17 on 2025-01-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
