# Generated by Django 4.2.17 on 2025-01-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title', 'slug']},
        ),
    ]
