# Generated by Django 4.2.17 on 2025-01-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title', 'slug']},
        ),
    ]
